### ISSUE TITLE
Sound Room the Back Room 

### ISSUE THREAD

**Issue by ghost** [DecentralVan/decentral#152]
Turning the backroom into podcasting vlogging studio. 
This is summary of a conversation with Zac

Ideal world: 
- Mic stands that are not touching the table. A square table with a hole in the middle is ideal because the mic will pick up sound of people touching the table. 
- Cover the walls and roof
- We need sound panels to be strategically placed along the walls, roof, pipes 
- We need at least one more microphone, ideally each person would have their own mic on separate volume control
- New sound board
- Squeak free stools with backs
- a rug that really brings the room together
- wireless lapel microphone

Expense Prediction: 
- soundproofing one full wall $286 or $150 per wall for multiple walls
- each additional microphone $179
- soundboard (digital USB) $200-300
- microphone stands (at least 2) $60
- pop filters $15 per mic
- build a table $50 (not metal)
- at least two non squeaky stools with backs $100 - $120 (ikea, but we must go test the squeaky)
- soft under padding for glasses and other clinky things $10
- foam for water pipes $30
- headphones $20 each
- a dedicated computer with a decent sound card $donation, hopefully
 
About $1070

Notes: 
 - we can attach foam around the door (most of the sound will come through the door.)
- sound panels can be moved to a new location 
- any sort of foam can wrap around the piping 
- A few large panels along the wall would make a big difference
- most concerned about the wall to the hallway because of the furnace buzzing sound. 
- the corner away from the radiator is the best spot for the recording 
- When sitting in stools you tend to move less, highly recommended
- Would like to have a setup that allows people to stand as well as sit (another pro stool arguments)
- Possible that sound studios around Vancouver would have extra / old soundproofing
- People talk directly into the microphone when it ideally should be pointing into the neck
- need a dedicated VOIP server like Mumble or something else with low latency
- Reeper is a good program for audio programming
- Lorne Lapham on boundary has good used headphones for $20 
- Zac could potentially donate a large portion of good equipment ($5000 worth) but wants some kind of assurance in case it gets stolen or damaged

**Comment by melodyma** [comment]
From friend:
Sounds like a decent plan. I personally don’t think you need to overthink it though. It’s nice to have a dedicated studio, but you can do a really great recording job with less…. I’d invest more into the microphones and headphones and less into other things.

headphones - make sure they are ‘closed’ which means they seal over the ear as opposed to sit on top.

cheap headphones are usually open and you get bleed… that goes into the microphone

You can spend a lot of money on soundproofing. Unless you have a line on used material you will probably spend a lot

BUT the good news is that you can just hang a thick duvet behind the speaker and it’s 80% efficient

A lot of people who do portable interviews will use this method.

an old moving blanket works well too

**Comment by paullucas** [comment]
I would recommend building an isolated vocal booth (large enough for 2 people) inside of the room, rather than trying to treat the room itself. Since it would be built with panels, you could always dissasemble the vocal booth if the room isn't being used for recording. It also means if you need to move to another space, you don't have to redo all the soundproofing. The vocal booth would only cost around $500 in materials. This also means it could be used for music recording, not just podcasting. 2 stools (already have), 2 mic stands (already have), 2 Electro Voice RE-20's, 2 XLR cables (already have), 2 ATH-M50 headphones, and a MOTU Ultralite MK3 interface would be all you'd need. Leave upgrading the microphones until last, as we already have 2 SM-58's. You'd probably want to run the MOTU Ultralite interface into the iMac from the main room. This is because doing professional audio work in Linux is still a nightmare for most DAW-based workflows.  You'd want something like Ableton or Logic in-terms of recording software. As well as a good set of VSTs for mixing work. You don't need a new soundboard as 2 proper preamps with good AD conversion is much more practical.

**Comment by findkiko** [comment]
@paullucas Agree about the panels-on-panels idea.

That MOTU thing looks a bit pricey, wouldn't something like this work well?
https://www.amazon.ca/Behringer-302USB-Premium-5-Input-Interface/dp/B005EHILV4

**Comment by cammyjee** [comment]
@findkiko I was looking at something similar but would need more XLR inputs for podcasting. 

https://www.amazon.ca/dp/B008O517IW/ref=pd_lpo_sbs_dp_ss_1?pf_rd_p=1977604502&pf_rd_s=lpo-top-stripe&pf_rd_t=201&pf_rd_i=B0039PPW60&pf_rd_m=A3DWYIK6Y9EEQB&pf_rd_r=01AQFMM68Q4YJ97BXW6F

It doubles as an audio interface which would be nice for minimalism / less cables, but the preamps probably aren't the best for recording vocals. but we could always swap it out with a nice audio interface when recording vocals. A lot of musicians these days have their own interfaces.
