### ISSUE TITLE
Workshop for creating a sole proprietorship.

### ISSUE THREAD

**Issue by ghost** [DecentralVan/decentral#37]
First Saturday of March, Roberta

**Comment by RobertaScarlett** [comment]
It would be great if I could get two volunteers to do a demo at the Sole proprietor workshop...the reason is it's a two step process, there's a name request which takes a couple of days and after that's completed then you complete the registration, I can't demo this unless I have a Name request #, which is why I'd want two volunteers rather than one. One to go through the Name request process and one to complete it.
It costs 31.50 to do the name search and 40.00 to register...I need one volunteer to go through the name search during the workshop, and the other volunteer to have already done the namesearch so I can demo the rest of the registration process and also go through the provincial and federal tax registration.  For the final part of the demo, I can use the remittance forms, confirmation letters etc from that I received doing this last month for Maelstrom DAO...
Also I meant the second weekend in March if that's cool w/ everyone and nothing else is scheduled...3/12/16 between 3 - 6 - Three parts...Registration, Maintenance/Reporting, and Ethics...

Let me know if you're interested, one volunteer will do a namesearch before the workshop (It's easy and I'll help you), the other will do it during the workshop...you'll need 31.50 for the namesearch, and 40.00 to complete registration...online it allows to you pay by credit card.

**Comment by findkiko** [comment]
Confirmed event, moved to Wiki.
