### ISSUE TITLE
Enumerate and prioritize technical (or more in-depth) projects

### ISSUE THREAD

**Issue by findkiko** [DecentralVan/decentral#66]
We're spread fairly thin right now, I think we need to list out the projects we have underway, order them by priority and work on them to create some wins and visible progress.

**Comment by findkiko** [comment]
Done via slack vote.

**Comment by findkiko** [comment]
Need to do this again, but better.

**Comment by chiselinc** [comment]
I'm closing this because it's a bit vague, and also i think we're doing well on organically moving toward it with the new bounty implementation. Taylor has built a great projects page outline on the new website, and we can maybe start listing things there (accompanied by the needs for supplies/hands on deck for each)
