### ISSUE TITLE
Keep eye out for replacement locker setup

### ISSUE THREAD

**Issue by chiselinc** [DecentralVan/decentral#75]
Figure out what we want to do in place of the existing lockers when Denny takes them? Mainly a priority to make sure the mini lock box is un-stealable

**Comment by findkiko** [comment]
These are readily available: http://vancouver.craigslist.ca/search/sss?sort=rel&query=lockers
I think they would be a solid purchase for $100-200 if we lose the existing ones. I don't think we need as many or as tall ones as we have currently. I've vacated several that were really just holding tools and parts for the last year, (now in the back room). Slightly wider (backpack friendly) ones might be better for us.

The real issue is what's the deal with the existing ones, how likely are we to lose them? And can we organise a truck to get some new ones at fairly short notice.

**Comment by findkiko** [comment]
Think this threat has passed, also we free'd up half already if Denny wants some.
